#!/bin/sh

SCRIPTS=/home/chapuni/llvm-project-scripts
PROJECTS=/home/chapuni/llvm-project

cd $PROJECTS
git checkout master
#git pull --ff-only
REPOS=`git submodule foreach -q 'echo $path'`
for x in $REPOS; do (cd $x; git fetch) & done
wait
for x in $REPOS; do (cd $x; git fetch) & done
wait
for x in $REPOS; do (cd $x; git checkout -f; git clean -fx; git reset --hard llvm.org/master); done
for x in $REPOS; do (cd $x; git push github) & done
$SCRIPTS/fetch.pl
wait
git checkout master
git push github master
#git push github master --tags
