#!/usr/bin/perl

($headsym) = `git symbolic-ref -q HEAD` =~ m=^refs/heads/(\S+)$=;

$cmd = <<EOS;
(git cat-file -e \$sha1 || git fetch --all);
fgrep -q \$sha1 .git/HEAD
  || (echo Checking out detached submodule \$path...;
        git checkout -q \$sha1)
EOS
    ;

$cmd = <<EOS if $headsym ne '';
(git show-ref -q $headsym && git checkout -q $headsym)
&& ((git cat-file -e \$sha1 || git fetch);
    (git rev-parse HEAD | fgrep -q \$sha1)
     || git merge --ff-only \$sha1)
|| ($cmd)
EOS
    ;

$cmd =~ s/[\r\n]/ /g;

exit system("git submodule foreach --quiet '$cmd'");
